// Mock data for testing if API is unavailable

export const mockCurrencyRates = {
  "2024-10-10": {
    gbp: {
      usd: 1.265,
      eur: 1.175,
      jpy: 185.5,
      chf: 1.145,
      cad: 1.735,
      aud: 1.945,
      zar: 23.45,
    },
  },
  "2024-10-11": {
    gbp: {
      usd: 1.27,
      eur: 1.18,
      jpy: 186.0,
      chf: 1.15,
      cad: 1.74,
      aud: 1.95,
      zar: 23.5,
    },
  },
  "2024-10-12": {
    gbp: {
      usd: 1.275,
      eur: 1.185,
      jpy: 186.5,
      chf: 1.155,
      cad: 1.745,
      aud: 1.955,
      zar: 23.55,
    },
  },
  "2024-10-13": {
    gbp: {
      usd: 1.28,
      eur: 1.19,
      jpy: 187.0,
      chf: 1.16,
      cad: 1.75,
      aud: 1.96,
      zar: 23.6,
    },
  },
  "2024-10-14": {
    gbp: {
      usd: 1.285,
      eur: 1.195,
      jpy: 187.5,
      chf: 1.165,
      cad: 1.755,
      aud: 1.965,
      zar: 23.65,
    },
  },
  "2024-10-15": {
    gbp: {
      usd: 1.29,
      eur: 1.2,
      jpy: 188.0,
      chf: 1.17,
      cad: 1.76,
      aud: 1.97,
      zar: 23.7,
    },
  },
  "2024-10-16": {
    gbp: {
      usd: 1.295,
      eur: 1.205,
      jpy: 188.5,
      chf: 1.175,
      cad: 1.765,
      aud: 1.975,
      zar: 23.75,
    },
  },
};

export const mockAvailableCurrencies = {
  usd: "US Dollar",
  eur: "Euro",
  jpy: "Japanese Yen",
  gbp: "British Pound Sterling",
  chf: "Swiss Franc",
  cad: "Canadian Dollar",
  aud: "Australian Dollar",
  zar: "South African Rand",
  nzd: "New Zealand Dollar",
  sek: "Swedish Krona",
  nok: "Norwegian Krone",
  dkk: "Danish Krone",
  pln: "Polish Zloty",
  czk: "Czech Koruna",
  huf: "Hungarian Forint",
  try: "Turkish Lira",
  rub: "Russian Ruble",
  inr: "Indian Rupee",
  cny: "Chinese Yuan",
  krw: "South Korean Won",
  sgd: "Singapore Dollar",
  hkd: "Hong Kong Dollar",
  mxn: "Mexican Peso",
  brl: "Brazilian Real",
  ars: "Argentine Peso",
  clp: "Chilean Peso",
  cop: "Colombian Peso",
  pen: "Peruvian Sol",
  uah: "Ukrainian Hryvnia",
  bgn: "Bulgarian Lev",
  hrk: "Croatian Kuna",
  ron: "Romanian Leu",
  rsd: "Serbian Dinar",
  mkd: "Macedonian Denar",
  all: "Albanian Lek",
  bam: "Bosnia and Herzegovina Convertible Mark",
  mdl: "Moldovan Leu",
  gel: "Georgian Lari",
  amd: "Armenian Dram",
  azn: "Azerbaijani Manat",
  kzt: "Kazakhstani Tenge",
  uzs: "Uzbekistani Som",
  kgs: "Kyrgyzstani Som",
  tjs: "Tajikistani Somoni",
  tmt: "Turkmenistani Manat",
  afn: "Afghan Afghani",
  pkr: "Pakistani Rupee",
  lkr: "Sri Lankan Rupee",
  bdt: "Bangladeshi Taka",
  npr: "Nepalese Rupee",
  btc: "Bitcoin",
  eth: "Ethereum",
  ltc: "Litecoin",
  bch: "Bitcoin Cash",
  bnb: "Binance Coin",
  eos: "EOS",
  xrp: "XRP",
  xlm: "Stellar",
  link: "Chainlink",
  dot: "Polkadot",
  yfi: "Yearn.finance",
  aave: "Aave",
  sushi: "SushiSwap",
  snx: "Synthetix",
  mkr: "Maker",
  comp: "Compound",
  lend: "Aave",
  bat: "Basic Attention Token",
  zrx: "0x",
  rep: "Augur",
  knc: "Kyber Network Crystal",
  lrc: "Loopring",
  mana: "Decentraland",
  enj: "Enjin Coin",
  sand: "The Sandbox",
  axs: "Axie Infinity",
  chz: "Chiliz",
  flow: "Flow",
  near: "NEAR Protocol",
  ftm: "Fantom",
  one: "Harmony",
  algo: "Algorand",
  atom: "Cosmos",
  icp: "Internet Computer",
  fil: "Filecoin",
  vet: "VeChain",
  hbar: "Hedera Hashgraph",
  xtz: "Tezos",
  egld: "Elrond",
  avax: "Avalanche",
  sol: "Solana",
  matic: "Polygon",
  ada: "Cardano",
  doge: "Dogecoin",
  shib: "Shiba Inu",
};
